version: '3'
services:
  postgres:
    image: postgres
    restart: always
    container_name: "postgres_programacao_modular"
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=pm
      - POSTGRES_USER=pm
      - POSTGRES_PASSWORD=pm
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
